genomes:
  - "ce11_1pct"

coverage_treat: [10]
coverage_ctrl:  [4]

tf_peak_count_treat: [5]
fragment_length: [150]
read_length:     [38]
tf_sigma:        [20]
tf_enrich:       [2500]
tf_exp:          [1.0]
seed:            [37]
gc_exp:          [0.6]
acc_exp:         [0.5]
acc_weight:      3.0
map_coverage_pct: [0]
map_sigma:        [1.5]
map_enrich:       [10]
map_exp:          [1.0]
nb_k:            [1000000]
emit_pmf_csv: false
result_root: "results_homer_broad"

aligners: ["bowtie2"]
peakcaller_list: ["homer"]
macs2_mode: ["broad"]
use_control: [true]

acc_beds:     ["bedA"]
gc_bias_sets: ["gcA"]

genome_paths:
  ce11_1pct: "data/genomes/ce11_1pct/ce11_1pct.fa"

accessibility_paths:
  ce11_1pct:
    bedA: "data/accessibility/ce11_1pct/bedA.bed"
    bedB: "data/accessibility/ce11_1pct/bedB.bed"

gc_bias_paths:
  gcA: "data/gc_bias/gcA.csv"
  gcB: "data/gc_bias/gcB.csv"

peakcallers:
  macs2:
    flags: "-f BAMPE --nomodel --extsize 147 --keep-dup all --nolambda -q 0.5"
    genome_size:
      ce11_1pct: "1.0e6"
  homer:
    style_by_mode:
      narrow: "factor"
      broad: "histone"
    flags_by_mode:
      narrow: ""
      broad: ""

indexes:
  ce11_1pct:
    bowtie2_index: "data/indexes/ce11_1pct/bowtie2_index/ce11_1pct"
    bwa_index:     "data/indexes/ce11_1pct/bwa_index/ce11_1pct"

params_table: "results_homer_broad/params/pilot_tfclean_homer_realistic_plateaus_wavy_broad_integrated_1_run_params.csv"
